k3s_version: v1.20.0+k3s2
ansible_user: ubuntu
systemd_dir: /etc/systemd/system
controlplane_ip: "{{ hostvars[groups['controlplane'][0]]['ansible_host'] | default(groups['controlplane'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

hosts:
  - "192.168.0.10    k3s-control"
  - "192.168.0.11    k3s-node01"
  - "192.168.0.12    k3s-node02"
  - "192.168.0.13    k3s-node03"
  - "192.168.0.14    k3s-node04"
  - "192.168.0.15    k3s-node05"
