- name: Configure k3s controlplane installation options
  template:
    src: etc/rancher/k3s/server.yaml.j2
    dest: /etc/rancher/k3s/server.yaml
    owner: root
    group: root
    mode: '0644'

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -s - --config /etc/rancher/k3s/server.yaml

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from controlplane
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store controlplane node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"
