- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: python-apt dependency
  shell: apt-get install -y python3-apt
  args:
    warn: no

- name: apt-get upgrade
  apt:
    upgrade: full
