apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/danderson/metallb//manifests?ref=v0.9.5
- configmap.yaml

namespace: metallb-system

#kubectl create secret -n metallb-system generic memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
